name: Auto getting data

on:
  schedule:
    - cron: '35 22 * * *'
  workflow_dispatch:

jobs:
  auto_getting_data:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run auto fetch data
        run: |
          python src/data/fetch_data.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add raw/*
          git commit -m "Updated raw data on `date` with GitHub Actions"
          git push origin master