on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  preprocess_air_data:
    needs: fetch_air_data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    outputs:
      sha_new: ${{ steps.sha_new_outputs_SHA_NEW }}
    permissions:
      contents: write
    steps:
      - env:
          SHA_NEW: ${{ needs.fetch_air_data.outputs.sha_new }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.fetch_air_data.outputs.sha_new }}
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: python39-mle-pipeline
      - name: Set up DVC
        uses: iterative/setup-dvc@v1
      - name: Download data with DVC
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          ls
          dvc pull -v -f -r origin
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run auto fetch data
        run: |
          python src/data/process_air_data.py
          python src/data/fetch_weather_history_data.py
          python src/data/process_weather_history_data.py
          python src/data/merge_air_weather_data.py
      - name: Add data to storage with DVC
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc add ./data/
          dvc push -r origin
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git rm -r --cached .
          git add .
          git commit -m "Updated raw data on `date` with GitHub Actions"
          git push origin master
      - name: Save git HEAD sha
        id: sha_new
        run: echo "SHA_NEW=${git rev-parse HEAD}" >> "$GITHUB_OUTPUT"