# https://www.programonaut.com/how-to-deploy-a-git-repository-to-a-server-using-github-actions/
# https://stackoverflow.com/a/70447517

name: Run deploy

on:
  push:
    branches:
      - master
    paths:
      - src
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git pull && docker-compose up -d && exit"
      - name: cleanup
        run: rm -rf ~/.ssh